# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/torch-mlir-notes',
                'doc_host': 'https://vguerra.github.io',
                'git_url': 'https://github.com/vguerra/torch-mlir-notes',
                'lib_path': 'torch_mlir_notes'},
  'syms': {'torch_mlir_notes.core': {'torch_mlir_notes.core.foo': ('core.html#foo', 'torch_mlir_notes/core.py')}}}
